### ISSUE TITLE
Workflow to Export VARIANT Products

### ISSUE THREAD

**Issue by marcus-hoppen** [akeneo/MagentoConnectorBundle#217]
We are still experiencing to the creation of configurable products. This workflow is known to us. The Question is how we can export the configurab le Product to the Magento Shop.
Is there any workflow or a manual to create a configurable product properly and export it in magento?

If we export products we've created for the configurable product, the products are be exported as simples but there is no creation of a configurable product in magento.

Can someone help on this issue?

Best Regards

**Comment by sineline** [comment]
Any news on how to define media for configurables?

**Comment by fitn** [comment]
Hi @sineline 

Sorry for late. I'm doing clean up on issues and I just saw your question.
It's already possible to define images for configurables in the last 1.1.*

Medias (other than images) are not handled by this connector because it's not managed by the Magento API. In our projects, we use SFTP specific integration for that.

Regards,
