### ISSUE TITLE
Export bundles

### ISSUE THREAD

**Issue by sumbobyboys** [akeneo/MagentoConnectorBundle#27]

**Comment by webtechns** [comment]
Any updates on this?  When you'll begin working on it, and estimated date you envision it being available, etc.?

Thanks so much!

**Comment by damien-carcel** [comment]
Eventually, this feature will not be added, as Akeneo doesn't handle bundles (nor downloadable or virtual products).
By the way, an option was added in the v1.1 to prevent their deletion on Magento during an export:
https://github.com/akeneo/MagentoConnectorBundle/commit/24a9be8c6c019c320d3ba69d902f9584553c9d10

Regards.

**Comment by webtechns** [comment]
I don't understand.  You said "Eventually", then you said "this feature will not be added".

Which one is it?

Are you saying Akeneo will never, ever, allow for the ability to work with bundle products?

**Comment by webtechns** [comment]
What happens if I have a bundle product in Magento, and I remove one of the simple products included in that bundle from Akeneo, then I export the product updates to Magento (removing that simple product)?

Will I get an error because of the bundle product, will it deactivate that bundle product, or will it delete than bundle product?

**Comment by damien-carcel** [comment]
Indeed, bundles will never be handle by Akeneo, as a bundle imply a notion of quantity and customization (which Akeneo doesn't handle).

Concerning your last question: any products removed from Akeneo will be removed from Magento on next export, even if it is used by a bundle, without error message. Logically, if you remove this product from Akeneo, that's because you don't have the use for it anymore, so your bundle have to be updated/removed in Magento.
But if for any reason, you must keep the bundle and all its related products, you can use the option "Do nothing" from the Magento connector product export, preventing the removal from Magento of Akeneo deleted products.
