### ISSUE TITLE
Only transfer changed fields

### ISSUE THREAD

**Issue by tempoecommerce** [akeneo/MagentoConnectorBundle#390]
The current export is taking really long. Also when you export the shop it creates new product images each time you export. This is not efficient.

**Comment by BitOne** [comment]
Hello @tempoecommerce,

The performance problem are caused by the Magento SOAP API. We are aware of that, and in the future version of the Magento Connector Bundle (v1.2), we will provide a working delta export, allowing to export only product that have changed.

For the images, I agree that this is not efficient to remove them and recreate them each time we export the product, but the Magento SOAP API doesn't allow to identify images, so we cannot know which images are already sent and present in Magento. So the only way to make sure that the images are correctly synchronized is to remove all of them and resend them for each product updated.

**Comment by cloudswork-ruud** [comment]
The only issue is that they are not removed from the servers file system.

I guess we have to live with this, cause magento won't change this in the near future :)
